"""recreate_missing_changes

Revision ID: 318a630c8019
Revises: 70e25ac4339c
Create Date: 2025-04-06 19:14:32.696337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '318a630c8019'
down_revision: Union[str, None] = '70e25ac4339c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('average_players_per_second', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'average_players_per_second')
    # ### end Alembic commands ###
