"""Added summary to the database

Revision ID: 60c2c6e2efa3
Revises: 7bf7371b4370
Create Date: 2025-04-05 15:10:42.610140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '60c2c6e2efa3'
down_revision: Union[str, None] = '7bf7371b4370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'summary')
    # ### end Alembic commands ###
