"""description

Revision ID: 70e25ac4339c
Revises: 0615b31a3109
Create Date: 2025-04-05 17:04:11.469300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e25ac4339c'
down_revision: Union[str, None] = '0615b31a3109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('average_players_per_second', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'average_players_per_second')
    # ### end Alembic commands ###
