"""Add new fields to model

Revision ID: 7bf7371b4370
Revises: defd8f3b98d7
Create Date: 2025-04-04 22:38:11.752479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf7371b4370'
down_revision: Union[str, None] = 'defd8f3b98d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('left_side_time', sa.Float(), nullable=True))
    op.add_column('video', sa.Column('right_side_time', sa.Float(), nullable=True))
    op.add_column('video', sa.Column('left_side_percentage', sa.Float(), nullable=True))
    op.add_column('video', sa.Column('right_side_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'right_side_percentage')
    op.drop_column('video', 'left_side_percentage')
    op.drop_column('video', 'right_side_time')
    op.drop_column('video', 'left_side_time')
    # ### end Alembic commands ###
