"""description

Revision ID: 9475c1e0b897
Revises: e62485948e8c
Create Date: 2025-03-20 19:46:01.843515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9475c1e0b897'
down_revision: Union[str, None] = 'e62485948e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('name', sa.String(length=255), nullable=True))  # Add the column as nullable
    op.execute("UPDATE video SET name = 'Untitled' WHERE name IS NULL")  # Set default value for existing rows
    op.alter_column('video', 'name', nullable=False)  # Make the column NOT NULL
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'name')
    # ### end Alembic commands ###
