"""description

Revision ID: d9a36bdf3aea
Revises: 78bbc54bc4a6
Create Date: 2025-03-20 19:07:16.964174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add this import for sqlmodel types


# revision identifiers, used by Alembic.
revision: str = 'd9a36bdf3aea'
down_revision: Union[str, None] = '78bbc54bc4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('datetime_uploaded', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['userinfo.user_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table(
        'video_statistics',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),  # Use sqlmodel type
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('userinfo.user_id'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_statistics')
    op.drop_table('video')
    # ### end Alembic commands ###
